services:
  - type: web
    name: my-pos
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "false"
      - key: APP_FULL_BASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: my_pos
      - key: SECURITY_SALT
        sync: false
